---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flowise 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flowise 
  template:
    metadata:
      labels:
        app: flowise
    spec:
      containers:
      - name: flowise
        image: flowiseai/flowise 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          #        env:
          #          - name: FLOWISE_USERNAME
          #            value: ""
          #          - name: FLOWISE_PASSWORD
          #            value: ""
        volumeMounts:
        - name: k8s-pv02 
          mountPath: /root/.flowise/storage
          subPath: flowise/storage
      volumes:
      - name: k8s-pv02 
        persistentVolumeClaim:
          claimName: synology-k8s-pv02 
